personio_py/__init__.py,sha256=m7du9bRYUv_kZTx6GTmpm3LXRwpItmMroyo81T9STzw,606
personio_py/client.py,sha256=0O_40rDbSwZVNM1KM7GaD-zKq1tFuI-VLu0ahBj27Hc,14702
personio_py/errors.py,sha256=UgFTWn6JGwXpIVYqehMlGrDz1FNN6rbFJlWPi11qBw0,2820
personio_py/mapping.py,sha256=eUYLP16RQrz8ER5ih9XGw7AtZgWU9W8yI7WoMTgvVlU,7739
personio_py/models.py,sha256=yPzvwOhMnIHqVTEK_7UTLZOp0Yib2ZJkjzgNhH54NFw,28311
personio_py/version.py,sha256=ls1camlIoMxEZz9gSkZ1OJo-MXqHWwKPtdPbZJmwp7E,22
personio_py-0.1.1.dist-info/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
personio_py-0.1.1.dist-info/METADATA,sha256=nBWGrQD6jzKZ-4SM-_8Xid8XMO49nf3L5DRtB71SZO4,7799
personio_py-0.1.1.dist-info/WHEEL,sha256=EVRjI69F5qVjm_YgqcTXPnTAv3BfSUr0WVAHuSP3Xoo,92
personio_py-0.1.1.dist-info/top_level.txt,sha256=fEuYcVTxEXQr6qK-FDqkf3D0ldenZz5yAWtHdGPp7rk,12
personio_py-0.1.1.dist-info/RECORD,,
